# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: openjdk:8u171-jdk-alpine
            - image: mysql:5.6
              command: mysqld --character-set-server=utf8mb4 --collation_server=utf8mb4_unicode_ci
              environment:
                MYSQL_ROOT_PASSWORD: empty
                MYSQL_ROOT_HOST: "%"